version: "3.7"

services:
  db:
    image: mongo:4.2-bionic
    env_file:
      - .env

  redis:
    image: redis:6.2

  sidekiq:
    build: .
    command: bundle exec sidekiq -r ./src/app/kafka/consumer.rb
    env_file:
      - .env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - sidekiq
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
