version: "3.7"

services:
  db:
    image: mongo:4.2-bionic
    env_file:
      - .env

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
